### PR TITLE
New scan command implemented

### PR DESCRIPTION
**Pull request by erikkaashoek**
Implemented a scan command with arbitrary length by modifying the sweep function
The can command pauses the sweep and then starts a on-demand sweep that writes the uncalibrated output instead of storing.
Usage of the scan command:
scan {start frequency in Hz} {step frequency in Hz} {number of steps}
Hope this is useful

### CODE REVIEW

**Comment by edy555** [comment]
Thanks for the proposal. Please give me some days to think about this feature.
Such as you proposed, it is needed to measure with more sweep points, I think.

**Comment by edy555** [comment]
I'm sorry for waiting for you long time.
I have plan to implement `sweep` command by myself. It would be fast and efficient without updating the screen. Thanks for your patience.
Next topic about fft, the update contributed by cho45 of preprocessing of TDR from your suggestion was just merged. I think your comment is very essential. Thanks for your contribution again.

**Comment by edy555** [comment]
Thanks for many proposals and comments. And sorry for the late response.

New `scan` command was added in #51 and this is the thing you need I believe.
Would you try to use in your pc tool?

**Comment by erikkaashoek** [comment]
Reading the code it seems the scan command is limited to 101 points due to using update_frequency. 
Is this correct? The intention was to allow arbitrary number of points thus using the frequency array should be avoided
Will you consider arbitrary number of points in the scan command?

**Comment by edy555** [comment]
I'm sorry that I can only say no. 
I'd like to keep the structure of firmware as standalone tools and interfacing to PC is not the first priority.

**Pull request closed without merging**
