### PR TITLE
Fix freq commands (parsed as int), more compact code

### PR DESCRIPTION
**Pull request by DiSlord**
Fix freq commands (parsed as int), more compact code

### CODE REVIEW

**Comment by DiSlord** [comment]
I think need remove 
 uint32_t _frequencies[POINTS_COUNT];
from properties_t

And calculate it on fly (not use float digit)

Its allow save big size of ram, and rom (and config size on flash)

**Comment by edy555** [comment]
> I think need remove
> uint32_t _frequencies[POINTS_COUNT];
> from properties_t
> And calculate it on fly (not use float digit)
> Its allow save big size of ram, and rom (and config size on flash)

Exactly. It might be possible. I'll think about it.

**Comment by DiSlord** [comment]
I can`t upload my version chprintf.c to ChibiOS\os\hal\lib\streams upload it to root :(

**Comment by edy555** [comment]
Awesome update, great!

BTW, the change below makes trouble, could you remove from this PR.
image

**Comment by edy555** [comment]
This update seems to contain LF+CR. It is better using only LF.

**Comment by DiSlord** [comment]
Seems better recreate pull Request or fork, i get errors on fix it
(In last commit i revert all changes to ChibiOS, and get errors)

**Comment by edy555** [comment]
I see, place PR again, please.

**Pull request closed without merging**
